sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  cron_job:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(kube_cronjob_info{}, 'cronjob', 'cluster')



