sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  bdb_name:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(bdb_conns{}, 'bdb', 'bdb_name')

  cluster:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(bdb_conns{}, 'bdb', 'bdb_name', 'job', 'cluster')




