sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  cassandra_instance:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(cassandra_cache_capacity{}, 'instance_name')

