sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  ec2_instance:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(node_total_req{}, 'job', 'instance')



