sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  instance:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(scylla_database_total_reads{})



