sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  job:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(pg_settings_max_connections{})



