sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  connector:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(confluent_kafka_connect_sent_bytes{}, 'connector_id')