sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  elasticsearch_jobs:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(elasticsearch_indices_search_query_total{}, 'job')


