sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  deployment:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(kube_deployment_labels{deployment!~'kube.*'}, 'deployment', 'cluster')



