sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  queue:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(rabbitmq_connections{}, 'job', 'instance')



