sources:
  prom:
    type: prometheus
    datasource: "${PROM_DATASOURCE}"

properties:
  topic:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(confluent_kafka_server_consumer_lag_offsets{}, 'topic')

  consumer:
    source_type: prometheus
    source_name: prom
    timeout: 10m
    query: label_map(confluent_kafka_server_consumer_lag_offsets{}, 'topic', 'consumer_group_id')




